name: Auto-update registry versions

on:
  workflow_dispatch:
  schedule:
    # At 04:31, every day
    - cron: 31 4 * * *

# Declare default permissions as read only.
permissions: read-all

jobs:
  auto-update-versions:
    name: Auto-update registry versions
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Remove the if statement below when testing against a fork
    if: github.repository == 'open-telemetry/opentelemetry.io'
    steps:
      - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: otelbot-token
        with:
          app-id: ${{ vars.OTELBOT_APP_ID }}
          private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Use CLA approved github bot
        run: |
          git config user.name otelbot
          git config user.email 197425009+otelbot@users.noreply.github.com

      - name: Auto-update
        run: |
          .github/workflows/scripts/update-registry-versions.sh
        env:
          # change this to secrets.GITHUB_TOKEN when testing against a fork
          # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ steps.otelbot-token.outputs.token }}
