name: Auto-update versions

on:
  workflow_dispatch:
  schedule:
    # hourly at minute 10
    - cron: 10 * * * *

permissions: read-all

jobs:
  auto-update-versions:
    name: Auto-update versions
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.repository == 'open-telemetry/opentelemetry.io'
    env:
      DEPTH: --depth 999 # submodule clone depth

    steps:
      - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: otelbot-token
        with:
          app-id: ${{ vars.OTELBOT_APP_ID }}
          private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4

      - name: Use CLA approved github bot
        run: |
          git config user.name otelbot
          git config user.email 197425009+otelbot@users.noreply.github.com

      - run: ./scripts/auto-update/all-versions.sh
        env:
          # change this to secrets.GITHUB_TOKEN when testing against a fork
          GH_TOKEN: ${{ steps.otelbot-token.outputs.token }}
